spring:
  application:
    name: TestTaskForDynamika

  datasource:
    driver-class-name: org.postgresql.Driver
    username: book-service
    password: 12345678
    url: jdbc:postgresql://localhost:5432/book-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
